### ISSUE TITLE
deterministic iteration vs. performance degradation

### ISSUE THREAD

**Issue by karussell** [carrotsearch/hppc#14]
We have intergrated hppc and made good success after setting a [constant HashOrderMixing](https://github.com/graphhopper/graphhopper/blob/master/core/src/main/java/com/graphhopper/coll/GHIntObjectHashMap.java) as we really need iteration to be deterministic. Now I think we had a chat where you recommended against such a solution, unfortunately I cannot find it anymore.

But we found some more explanation [here](https://github.com/carrotsearch/hppc/blob/0.8.1/hppc-examples/src/test/java/com/carrotsearch/hppc/examples/HppcExample_006_HashAndScatterMaps.java).

There are still a few things that I do not understand and maybe you can help us :) ?

Why is this (partial) copying into the same implementation such a big problem that the design of the collection is heavily influenced? It seems you even plan to introduce an iterationSeed in 0.9?

Is the deterministic iteration really the problem and not something "good"? Wouldn't it be better to solve the problem when adding many elements e.g. a special "addAll" method that takes the collection and the element count or some kind of an "Acceptor" or "Filter"? Then it can internally handle the cluster problem when copying into other collections and you can still maintain deterministic iteration.

We probably have too seldom uses where we (partially) copy maps into other maps, but when exactly are those clusters created? Because as soon as the map has a different size the hashing should be different and the clustering should be less of a problem (?)

**Comment by dweiss** [comment]
The discussion is scattered across several issues...
https://issues.carrot2.org/browse/HPPC-103

In short: if it's an associative data structure, don't expect the same layout of keys between runs... This can change not just because of key mixing strategies but also due to changes in the algorithm, etc.

@bruno-roustant has provided an improvement which removes key redistribution strategies in favor of shuffled iteration order (used when copying). This is a nice improvement. In general though, the cleanest approach is to treat associative containers for what they are; if you need a constant key order (for tests or otherwise), copy and sort the keys afterwards.

> but when exactly are those clusters created?

That example code snippet has an example of why exponential scans start to occur. If you revert back to a version prior to the issue being discovered you can make a simple putAll operation easily block forever.

**Comment by karussell** [comment]
Thanks for the prompt reply and of course also for pushing this project forward :+1: !

> https://issues.carrot2.org/browse/HPPC-103

In the issue you write:

> So when we do a putAll we're essentially adding keys that have nearly-sorted (except for the wrap-up case) hashes. 

Why couldn't it be solved fully inside putAll like setting a random iteration seed?

And why isn't there such a risk for the normal java.util.HashMap implementation?

> This can change not just because of key mixing strategies but also due to changes in the algorithm, etc.

A change from one version to another is not a problem. We are looking for deterministic behaviour for the same binary. 
(So if I use the same openstreetmap input it should produce the same road network and also if I have a road network two route requests from A to B should always give me the same external and internal results, which both is not the case for random iteration order). 

Otherwise debugging, bug reproduction and bug fixing will be much more complicated. And an added complexity to ensure this order would decrease performance by a lot.

> if you need a constant key order (for tests or otherwise), copy and sort the keys afterwards.

For tests this sounds doable but in general this would be likely a too heavy speed loss.

> @bruno-roustant has provided an improvement which removes key redistribution strategies in favor of shuffled iteration order (used when copying).

Ok. For my reference: https://github.com/carrotsearch/hppc/pull/10#issuecomment-678231799 ;)

and also: https://github.com/vsonnier/hppcrt/issues/38 and https://issues.carrot2.org/browse/HPPC-186

Maybe the biggest question for us is if in 0.9.x, will there be still a possibility to force deterministic iteration order? (like in the constructor)

**Comment by dweiss** [comment]
java.util.HashMap has an entirely different internal implementation - that's why it's not a problem there.

> So if I use the same openstreetmap input it should produce the same road network

It does work as expected, it's just not a list - it's a *set*. That's why I suggested sorting whatever your keys are afterwards if you need reproducible iteration. It's much the same with other things that are set-like: filesystem iteration order - not guaranteed, even if sometimes consistent between runs. When you use Java's HashMap the order of iteration is also not guaranteed - it can vary between vendors and releases. There is a special class LinkedHashMap that does provide insertion-order iteration guarantee. HPPC doesn't have such a data structure. 

> Maybe the biggest question for us is if in 0.9.x, will there be still a possibility to force deterministic iteration order? (like in the constructor)

I don't think we can make such guarantees. Again: by design it's a set. When you're iterating over that, the order of iteration is not defined and should not be relied on. If this causes non-determinism up the stack, that means your code is buggy (it should ensure sets are converted to consistently ordered streams). In many applications this is not an issue - they only care about containment and/or key-value pairs.

Again: we provide sets, not lists. Iteration order is undefined (other than guaranteed to exhaust all elements added to the set).

**Comment by bruno-roustant** [comment]
Indeed this issue is complex, and really due to the open-addressing internal collision resolution technique. This technique makes the map fast and compact, but it has this drawback (among others). Even if the maps were of different sizes, the issue would remain.

@karussell, as I understand your need is to have a constant ordering of the iteration (when iterating with iterator() or forEach()), do you confirm? Maybe we could let randomly shuffled iteration by default (to be used by all copy methods to avoid the issue) and have some way to get a constant ordering when the iteration is called explicitly for that purpose (not for a copy but by the caller)?
I could work on that if you both agree it could fit. I would take some volunteering hours for openstreetmap :)
What is your opinion Dawid?

**Comment by easbar** [comment]
Thanks for your work on HPPC and giving more insight here! I think I understand the issue of collision avalanches when copying to another hash container up to the point that it needs to be addressed for HPPC to be usable as general purpose library. I also understand that by definition a hash set has an undefined iteration order. 
However, adding an 'artificial' iteration seed to the iterator will certainly add an element of surprise for users, especially when debugging an issue in user code that might only occur for a certain iteration order. I am not talking about code that only works for some iteration it expects even though it should not. I am talking about a specific iteration order that might lead to a specific problem that otherwise cannot be reproduced under otherwise same conditions. Therefore, I think making sure the iteration order stays the same when running the same binary multiple times is important. Luckily, on current master this seems to be the case because the iteration seed is always counted up from zero (and does not include something like the current time etc.). Can you confirm and will this property be maintained in the future?
And does the seeded iteration order come with a performance penalty? I think one of HPPC's strong points is that it comes (and I am citing the readme here) 'with open internals'. Therefore users who are aware of the collision avalanche problem and take care to not run into this problem (e.g. by creating the target container with the size of the origin container) should be able to iterate the hash container without performance loss and without the added complexity of a seeded iteration order in my opinion. So far this was possible by using ScatterMap. Now that ScatterMap is gone this should be possible to do at least by sub-classing the HPPC container (and ideally without the need to override a lot of code). Maybe making `iterationIncrement` protected and non-static would be enough?

Bonus question: I think I have a proper understanding of HPPC's implementation of the hash container with open addressing and linear probing and thought about the collision avalanche problem for some time. Still, I was unable to actually pin-point the reason why adding the hash container's elements to another container with the same hash order and using the storage order as iteration order systematically leads to the clustering at lower slots. The thing I am struggling with the most is that in the examples I was trying to come up with the target container always seems to resize before serious clustering can occur. Is this related to the array lengths always being a power of two? I'd be very glad if you could give a detailed explanation or point to some example, older issue etc. where this is explained.

**Comment by bruno-roustant** [comment]
> Luckily, on current master this seems to be the case because the iteration seed is always counted up from zero (and does not include something like the current time etc.). Can you confirm and will this property be maintained in the future?_

I see no reason to change, and I think this property should remain. The seed does not need to be random, it needs to change from one instance to another. Calling a random function or a time function would not add more safety and would cost some cpu.

> And does the seeded iteration order come with a performance penalty?

No performance penalty. Compared to the previous ScatterMap, this seeded iteration adds only 2 calls during the iteration constructor, and then the iteration is the same. One call to nextIterationSeed() which is the fast mixPhi and one call to iterationIncrement() which is a couple of basic int operations. Benchmarks showed that the small hop (increment) in the array during the iteration (instead of a +1 for ScatterMap) introduces no perf penalty.

> Therefore users who are aware of the collision avalanche problem and take care to not run into this problem (e.g. by creating the target container with the size of the origin container)

The collision avalanche problem happens during the copy, because the iteration is in the order of the key hashes which is the same for both containers. See below for an step-by-step description of the problem.
Creating the target container with the size of the origin container does not solve the collision avalanche problem.

> should be able to iterate the hash container without performance loss and without the added complexity of a seeded iteration order

There should not be any performance loss. Did you measure a loss?
Could you be more specific about the added complexity? The container usage is the same, this iteration order should be transparent, unless you have a strong need for a constant iteration order but this is not about complexity.

> Now that ScatterMap is gone this should be possible to do at least by sub-classing the HPPC container

That could be possible but I'm concerned that it may lead to improper use and again collision avalanches. I see the need for a constant iteration order not during copy. But I still don't see the need for a ScatterMap-like behavior, maybe you could share a benchmark to show the performance gain with a simple +1 iteration?

> Still, I was unable to actually pin-point the reason why adding the hash container's elements to another container with the same hash order and using the storage order as iteration order systematically leads to the clustering at lower slots.

I'll try to give a step-by-step small example.

When a key is added, based on open-adressing, it goes to the slot H of the array where H is its hash. Or if the slot H isn't empty (hash collision resolution), to the next empty slot on its "right" by loop-scanning +1 on the next slots in the array. This loop-scan is very important here, as it is the cause of the collision avalanche problem.
Also, the more the container is loaded (load of the internal array), the more collision avalanches.

So let's say we have a source container S with a internal array of capacity 16. 12 keys were added. So it is at the maximum load before resizing (0.75 by default).
For the example, we will not look at what the keys are, but at their hash (mod the array size) instead.

 `| . | 1 | 1 | 3 | 1 | 2 | . | . | . | 9 | 10 | 10 | 11 | 9 | 12 | 9 |`

When the key with h=2 (hash mod 16) was added, there was a loop-scan of 3 hops, starting from its ideal slot, to find an empty slot.

Now we copy the source container S to an empty target container T of same capacity. We iterate the keys in the source container in the array aorder, which is the sorted order of their (hash mod 16).

` | . | 1 | . | . | . | . | . | . | . | . | . | . | . | . | . | . |`
 
 `| . | 1 | 1 | 3 | . | . | . | . | . | . | . | . | . | . | . | . |` => second key h=1 needs a loop-scan of 1 hop.

 `| . | 1 | 1 | 3 | 1 | 2 | . | . | . | . | . | . | . | . | . | . |` => fourth key h=1 needs a loop-scan of 3 hops, fifth key h=2 needs a loop-scan of 3 hops.
 
 and so on
 
 Initially when adding the keys to the source container S, the keys hashes were in random-like other (thanks to the awesome mixPhi). This allowed open-addressing to find quickly empty slots, so the number of loop-scan hops was relatively small.
 But when adding to the target container T, the keys hashes are in sorted order, provoking a lot of loop-scan hops to find empty slots for many keys. When the source container is large and heavy loaded, it results in a lot of wasted time.
 
 The idea with the shuffled iteration order is that we iterate the keys not in the array order, but starting at a seed-based initial slot and we move to the next key with a small seed-based increment. This results in a random-like key order which lets much more empty slots while we add the key in the target container.

**Comment by easbar** [comment]
Thanks for the quick response!

> I see no reason to change, and I think this property should remain. The seed does not need to be random, it needs to change from one instance to another. Calling a random function or a time function would not add more safety and would cost some cpu.

Ok, good. Now I thought about this again another problem could be a 'server-like' scenario, where one request might produce some problem in user-code, but sending the same request again does not, because the iteration seed gets incremented for every request. For this reason even the fixed seed might make debugging such an issue more complicated, because it introduces global state (requests are not entirely independent from each other).

> Benchmarks showed that the small hop (increment) in the array during the iteration (instead of a +1 for ScatterMap) introduces no perf penalty.

Ok, that is good news. I did not do any performance benchmarks myself and was just speculating that incrementing with the increment > 1 (and therefore scanning the array multiple times) might be slower than +=1.

> Could you be more specific about the added complexity? The container usage is the same, this iteration order should be transparent, unless you have a strong need for a constant iteration order but this is not about complexity.

Ok, the only things I was concerned about were the possible slower iteration (but you said += increment is not really slower than += 1) and the 'unpredictable' iteration order (see above).

> I'll try to give a step-by-step small example.

Thanks a lot for this! What you are describing is essentially this scenario, right?

https://github.com/carrotsearch/hppc/blob/93c8fc52c384182229ce2a661417f40a58c5325a/hppc-examples/src/test/java/com/carrotsearch/hppc/examples/HppcExample_006_HashAndScatterMaps.java#L151-L181

So the keys array is essentially filled from left to right and the collisions (and loop-scan hops) we had in the source container happen again in the target container. Assuming we only copy some elements of the source container this is certainly not ideal (or even the worst case). But if we copied the whole container this way these loop-scan hops would be unavoidable anyway. Unless of course we simply did a low-level copy of the raw array. So yes if we do a partial copy we end up with a very bad key distribution (only the left part of the keys array is occupied), but this does not cause a real 'dead lock' yet. In fact copying the whole container this way (with the target container being initialized with the source container's size) still finishes relatively quickly.

The more serious problem arises if the target container is empty initially. This is the scenario described here: 

https://github.com/carrotsearch/hppc/blob/93c8fc52c384182229ce2a661417f40a58c5325a/hppc-examples/src/test/java/com/carrotsearch/hppc/examples/HppcExample_006_HashAndScatterMaps.java#L189-L266

It seems like because the target container is smaller we systematically get cluster chains in the left part of the array, but I do not really get why this is the case. I tried to understand this with a similar example as you using 16 elements and then 'copying' it to an empty container, but just before collisions can stack up the target container always seems to be resized. Resizing the target container means the elements are redistributed to higher slots so some of the existing clusters are cleaned up again and I am wondering under which condition the existing elements make additional collisions more likely (this would produce an 'avalanche' as collisions lead to longer cluster chains which in turn make it even more likely that there are conditions etc.)

**Comment by dweiss** [comment]
About iteration order -- this really is an experience standpoint for me to *not* guarantee iteration order... I understand why it may seem wrong at first, but believe me that embracing this non-determinism (for sets of values!) is going to be beneficial in the long run. I've been there before. We had all kinds of tests (from unit to integration) that turned out to depend on iteration order of java.util.Set/Map classes. Whenever the implementation in the JDK changed all our tests turned red... It was a painful process to update.

I don't think debugging gets more difficult because of random ordering of elements... if you design your software knowing the iteration is not defined. Say, for example - you need to compute a hash of elements in the set. If you know they can come in any order, either sort and hash them or use a hash function that is order-independent. It's a similar case with most problems - if you know and plan ahead for randomness, things get easier in the end.

This said, if you don't wish to have a random iteration order - use your own iterator on top of the underlying implementation (just scan all set elements from the underlying buffer left to right). It's not pretty but efficient and as long as the implementation of the element-distributor doesn't change, the result will be consistent.

As for avalanching - the problem is that the keys at the source object are effectively ordered by the output of the hash function. When you're adding to a smaller container it grows slower than the source and higher bits get discarded by the mask. This means after some expansions elements must scan from their bucket position all the way to an empty space (and all spaces will be taken because the difference is just on higher bits). I don't know how to explain it better than I already did in that sample test. Just run it until it freezes and look at what's happening in debug mode.

Finally - I just wanted to emphasis that to me trying to avoid this "runtime deadlock" problem is far more important than anything else. I know Sebastiano Vigna (fastutil) used to just resize the target container to (size(a) + size(b)) on putAll but this didn't work for me because I deal with collections close to array size boundary in Java... Maybe Sebastiano came up with something new though - he's a genius.

**Comment by easbar** [comment]
> This said, if you don't wish to have a random iteration order - use your own iterator on top of the underlying implementation (just scan all set elements from the underlying buffer left to right). It's not pretty but efficient and as long as the implementation of the element-distributor doesn't change, the result will be consistent.

Ok, yes having some some low-level way to do this is certainly helpful.

> Finally - I just wanted to emphasis that to me trying to avoid this "runtime deadlock" problem is far more important than anything else. 

I agree its important to provide a built-in solution for this. I also liked the possibility to opt-out of this as was the case with Hash/ScatterMaps in 0.8.

**Comment by bruno-roustant** [comment]
About non-determinism of iteration order, I just discovered a presentation for JDK 9+ Collections, and there is a chapter specifically about Randomized Iteration Order: new Set and Map iteration order is now randomized.
https://www.youtube.com/watch?v=lwp2RZ__0ko&t=1143s

**Comment by easbar** [comment]
He basically says that 1) the iteration order of maps and sets was and still is unspecified, 2) the iteration order often was stable across jdk versions 'by accident' (simply because the implementation did not change), 3) some user code relies on the iteration order even though it should not and 4) they randomize the iteration order in new collection types for this reason (so false usage can be detected early).

I can see how the randomization makes the JDK collections more 'idiot-proof' to use, but at the same time it seems odd to me to introduce such a randomization just to have this extra safety. I think having a deterministic iteration order between different runs can be a huge time-saver. Not to write code that actually relies on the iteration order, but to be able to easily reproduce the same application state during debugging. If you ask me having at least some opt-in kind of way to fix the determination order makes hppc a more useful library.

**Comment by dweiss** [comment]
Bruno - yes, this was done in part to avoid problems with DoS attacks too (you could prepare keys in advance and cause long conflict chains). 

If you rely on predictable iteration order of associative data structures (implicitly or explicitly) then sooner or later your software will break. Sorry, but it's experience speaking through me. Use appropriate data structure if you need this property -- JDK has linked hash map, tree maps, etc. HPPC doesn't have a collection like this; I never had the need for it.

**Comment by easbar** [comment]
> If you rely on predictable iteration order of associative data structures 

I don't. Don't you get my point?

**Comment by dweiss** [comment]
I re-read your comment again and now I think I get your point. Reading on a phone doesn't help understanding. Sorry.
