### ISSUE TITLE
 Iteration problem

### ISSUE THREAD

**Issue by TheLudlows** [carrotsearch/hppc#35]
I have two IntIntHashMaps that contain the same, but the iteration results are different.
How can the same map get the same iteration results?

**Comment by bruno-roustant** [comment]
My first question would be why do you need the same iteration, which use-case?
(the different iteration is on purpose)

Anyway you can use the SortedIterationIntIntHashMap to wrap each IntIntHashMap. It provides a sorted iteration order according to the comparator you provide.

**Comment by dweiss** [comment]
The changing iteration order (and unpredictable ordering of associative data structures) is there by design - don't try to change it, it will backfire. See this issue:

https://issues.carrot2.org/browse/HPPC-186

and related issues referenced from there to see why this can result in a deadlock.

If you need a predictable iteration order, use the recently added SortedIterationKTypeVTypeHashMap (it's a view) or change your code to work with arbitrary-order maps (sort keys yourself, change assertions in unit tests to be set-based, etc.).

**Comment by dweiss** [comment]
Good morning, @bruno-roustant . :)

**Comment by bruno-roustant** [comment]
And happy new year :)
Nice comment race!
